# Generated by Django 5.0.6 on 2026-05-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección / Ubicación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre o número identificador del edificio', max_length=50, verbose_name='Nombre / Número')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='infrastructure.site', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'db_table': 'buildings',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Identificador del ala (ej: 'A', 'B', 'Norte')", max_length=20, verbose_name='Nombre / Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wings', to='infrastructure.building', verbose_name='Edificio')),
            ],
            options={
                'verbose_name': 'Ala',
                'verbose_name_plural': 'Alas',
                'db_table': 'wings',
                'ordering': ['building', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Número / Identificador')),
                ('capacity', models.PositiveSmallIntegerField(help_text='Número máximo de estudiantes que puede alojar el cuarto', verbose_name='Capacidad máxima')),
                ('current_occupancy', models.PositiveSmallIntegerField(default=0, help_text='Se actualiza automáticamente con las asignaciones activas', verbose_name='Ocupación actual')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar para cuartos fuera de servicio sin eliminarlos', verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='infrastructure.wing', verbose_name='Ala')),
            ],
            options={
                'verbose_name': 'Cuarto',
                'verbose_name_plural': 'Cuartos',
                'db_table': 'rooms',
                'ordering': ['wing', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='wing',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='uq_building_wing'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('wing', 'number'), name='uq_wing_room'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('current_occupancy__lte', models.F('capacity'))), name='chk_occupancy_lte_capacity'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='chk_capacity_positive'),
        ),
    ]
