# Generated by Django 5.0.6 on 2026-05-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='gender',
            field=models.CharField(choices=[('Varones', 'Varones'), ('Hembras', 'Hembras'), ('Mixto', 'Mixto')], default='Mixto', help_text='Define qué sexo de estudiantes aloja el edificio', max_length=10, verbose_name='Sexo de los estudiantes'),
        ),
    ]
