# Generated by Django 5.0.6 on 2026-05-21 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(verbose_name='Fecha de asignación')),
                ('released_date', models.DateField(blank=True, help_text='NULL indica que la asignación está activa', null=True, verbose_name='Fecha de liberación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='infrastructure.room', verbose_name='Cuarto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='actors.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asignación de Cuarto',
                'verbose_name_plural': 'Asignaciones de Cuartos',
                'db_table': 'assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(verbose_name='Fecha asignada')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('evaluation', models.CharField(blank=True, choices=[('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal')], max_length=1, null=True, verbose_name='Evaluación de la tarea')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_schedules', to='infrastructure.room', verbose_name='Cuarto a limpiar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_schedules', to='actors.student', verbose_name='Estudiante asignado')),
            ],
            options={
                'verbose_name': 'Cuartelería',
                'verbose_name_plural': 'Cuartelerías',
                'db_table': 'cleaning_schedules',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la queja')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('type', models.CharField(choices=[('administrativa', 'Administrativa'), ('educativa', 'Educativa')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('visibility', models.BooleanField(default=False, verbose_name='Visible para otros estudiantes')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='infrastructure.building', verbose_name='Edificio relacionado')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='actors.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de evaluación')),
                ('grade', models.CharField(choices=[('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal')], max_length=1, verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario del instructor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='actors.student', verbose_name='Estudiante evaluado')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('expires_date', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible para estudiantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informations_created', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'Información',
                'verbose_name_plural': 'Informaciones',
                'db_table': 'information',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del reporte')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de reporte')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Parámetros')),
                ('file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL del archivo PDF')),
                ('generated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de generación')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_generated', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reports',
                'ordering': ['-generated_date'],
            },
        ),
    ]
