# Generated by Django 5.0.6 on 2026-05-27 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de la queja'),
        ),
    ]
