# Generated by Django 5.0.6 on 2026-05-21 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='ID de Empleado')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'professors',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, unique=True, verbose_name='Carné de Identidad')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Matrícula / Expediente')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección particular')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia')),
                ('municipality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de familiar')),
                ('illnesses', models.TextField(blank=True, null=True, verbose_name='Enfermedades')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='Medicamentos')),
                ('is_militant', models.BooleanField(default=False, verbose_name='Militante UJC/PCC')),
                ('is_cadet_minint', models.BooleanField(default=False, verbose_name='Cadete MININT')),
                ('is_cadet_far', models.BooleanField(default=False, verbose_name='Cadete FAR')),
                ('academic_performance', models.TextField(blank=True, null=True, verbose_name='Aprovechamiento Docente')),
                ('disciplinary_process', models.TextField(blank=True, null=True, verbose_name='Proceso Disciplinario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.group', verbose_name='Grupo Académico')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'students',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dean', serialize=False, to='actors.professor', verbose_name='Profesor')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dean', to='academic.faculty', verbose_name='Facultad supervisada')),
            ],
            options={
                'verbose_name': 'Decano',
                'verbose_name_plural': 'Decanos',
                'db_table': 'deans',
            },
        ),
        migrations.CreateModel(
            name='GroupAdvisor',
            fields=[
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='group_advisor', serialize=False, to='actors.professor', verbose_name='Profesor')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='group_advisor', to='academic.group', verbose_name='Grupo asesorado')),
            ],
            options={
                'verbose_name': 'Profesor Guía',
                'verbose_name_plural': 'Profesores Guías',
                'db_table': 'group_advisors',
            },
        ),
        migrations.CreateModel(
            name='WingSupervisor',
            fields=[
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wing_supervisor', serialize=False, to='actors.professor', verbose_name='Profesor / Instructor')),
                ('wing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wing_supervisor', to='infrastructure.wing', verbose_name='Ala supervisada')),
            ],
            options={
                'verbose_name': 'Responsable de Ala',
                'verbose_name_plural': 'Responsables de Ala',
                'db_table': 'wing_supervisors',
            },
        ),
        migrations.CreateModel(
            name='YearLeadProfessor',
            fields=[
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='year_lead_professor', serialize=False, to='actors.professor', verbose_name='Profesor')),
                ('career_year', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='year_lead_professor', to='academic.careeryear', verbose_name='Año Académico supervisado')),
            ],
            options={
                'verbose_name': 'Profesor Principal de Año',
                'verbose_name_plural': 'Profesores Principales de Año',
                'db_table': 'year_lead_professors',
            },
        ),
    ]
